# Generated by Django 6.0 on 2026-02-22 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Todo', '0002_todos_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='content',
            new_name='description',
        ),
    ]
