"""initial_setup

Revision ID: 5458b6cf02fb
Revises: 
Create Date: 2026-02-16 17:27:47.163145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5458b6cf02fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todoitemdb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todoitemdb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
